### ISSUE TITLE
No contribution guide / tooling

### ISSUE THREAD

**Issue by dandelionmane** [nippur72/PolymerTS#37]
There isn't a guide on contributing to this repository, and as a contributor it isn't clear what tools should be run to generate the js, typing files, minified js, et cetera, in a way that's consistent with previous releases. 

Perhaps setting up a simple gulp workflow is in order?

**Comment by nippur72** [comment]
true, that's mostly due to current VS2015 not handling `tsconfig.json` (but it's going to be fixed).

So simply I build from VS, and then run `ugly.bat` for the minification.

If you want to add a gulp workflow, it's welcome. It should run `tsc` first and then `uglify`, but we have to align `tsconfig.json`.

**Comment by jjrv** [comment]
The build is so simple that gulp is not needed. I made a PR that allows running `npm install` to build and minify.

**Comment by kito99** [comment]
Related to #106

**Comment by kito99** [comment]
Fixed in 0.2.3 branch.
