### ISSUE TITLE
Classes do not inherit Typescript properties from Behaviors?

### ISSUE THREAD

**Issue by danmane** [nippur72/PolymerTS#39]
expected: if I have a behavior that defines a new member for the Typescript class, that member is implicitly mixed in to classes that reference that behavior via the decorator.

actual: the member is not mixed in, so that referencing it in the class using the behavior creates a type error.

is fixing this feasible within the constraints of typescript decorators?

**Comment by nippur72** [comment]
Unfortunately it can't be fixed.

Please note this is the same issue that TypeScript mixins have, and hopefully we can get this fixed in some future releases of TypeScript (see [TypeScript/issues/2919](https://github.com/Microsoft/TypeScript/issues/2919)).

Until this is fixed, you have to manually add an empty signature, e.g. (see `test_components.ts`):
```TypeScript
methodInBase: ()=> void;

methodInChild() {
   return this.methodInBase();
}
```
or, alternatively use an ugly cast:
```TypeScript
methodInChild() {
   return (this as BehaviorBaseTest).methodInBase();
}
```
